#!/bin/bash
command -v fzf >/dev/null 2>&1 || {
    echo >&2 "fzf required but not installed"
    exit 1
}

m3u=$1

config_path="$HOME/.config/iptv/"
channels_file="$config_path/channels"
m3u_url_file="$config_path/m3u_url"
tmp_playlist="/tmp/iptvplaylist"

mkdir -p "$config_path"

usage() {
    cat <<EOF
usage: iptv [M3U_URL]

    [M3U_URL]    URL to a M3U playlist, required on first run
    --help       Display help
EOF
}

iptv_save_channels() {
    m3u_url=$(cat "$m3u_url_file")

    printf "\nLoading channels... "
    curl -s "$m3u_url" | grep EXTINF: -A 2 >$tmp_playlist
    # cat "$m3u_url" | grep EXTINF: -A 2 >$tmp_playlist
    printf "Done!\n"

    printf "Parsing channels... "
    channels=()
    url=""

    while IFS= read -r line; do
        if [[ "$line" =~ tvg-name=\"([^\"]+)\" || "$line" =~ tvg-id=\"([^\"]+)\" ]]; then

            name="${BASH_REMATCH[1]}"
            url=""
            title=""

            # pattern="group-title=\"([^\"]+)\""
            pattern="group-title=([^*$]+)"
            if [[ "$line" =~ $pattern ]]; then
                title=" - ${BASH_REMATCH[1]}"
            fi

        elif [[ "$line" == http* ]]; then
            url="$line"
            channels+=("$name$title - [CH:${#channels[@]}] url:$url")
        fi
    done <"$tmp_playlist"

    printf "Done!\n"

    printf "%s\n" "${channels[@]}" >$channels_file
}

iptv_send() {
    send-to-kodi.sh -s
    sleep 2s
    send-to-kodi.sh "$selected_channel_url"
}

iptv_main() {

    selected=$(cat "$channels_file" | sed 's/ [^ ]*$//' | fzf)

    if [ ! -n "$selected" ]; then
        exit 1
    fi
    if [[ "$selected" =~ ^(kodi)$ ]]; then
        unset selected
        kodi_main
    fi    

    selected_channel=$(echo "$selected" | sed 's/.*\(\[CH:[0-9]\+\]\).*/\1/')
    selected_channel_line=$(cat "$channels_file" | grep -F "$selected_channel")
    selected_channel_url=$(echo "$selected_channel_line" | grep -oE 'url:(.*)' | sed 's/url://' | tr -d '\r')
    selected_channel_name=$(echo "$selected_channel_line" | sed 's/\(.*\) url:.*/\1/')

    printf "Sending %s to Kodi\n" "$selected_channel_name"
    iptv_send $selected_channel_url
    iptv_main
}

if [ -z "$m3u" ] && [ ! -s "$channels_file" ]; then
    usage
    exit 1
fi

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
    usage
    exit 0
fi

if [ ! -z "$m3u" ]; then
    echo "$m3u" >$m3u_url_file
    iptv_save_channels
    echo "Playlist saved. Now run iptv again without a M3U URL."
    exit
fi

if [[ $(find "$channels_file" -mtime +1) ]]; then
    printf "Doing a daily update of channels..\n"
    iptv_save_channels
fi

# iptv_main
