#!/usr/bin/env bash

iptv_main() {

    unset INPUT
    iptv_load

    selected=$(cat "$channels_file" | sed 's/ [^ ]*$//' | fzf --header='CTRL-c or ESC to quit' )

    if [ -n "$selected" ]; then
        selected_channel=$(echo "$selected" | sed 's/.*\(\[CH:[0-9]\+\]\).*/\1/')
        selected_channel_line=$(cat "$channels_file" | grep -F "$selected_channel")
        selected_channel_url=$(echo "$selected_channel_line" | grep -oE 'url:(.*)' | sed 's/url://' | tr -d '\r')
        selected_channel_name=$(echo "$selected_channel_line" | sed 's/\(.*\) url:.*/\1/')

        check_url "$selected_channel_url"
        
        printf "Sending: %s\n" "$selected_channel_name"
        INPUT="$selected_channel_url"
        unset selected
        kodi_main
    fi    
    
}