#!/bin/bash

iptv_save_channels() {
    m3u_url=$(cat "$m3u_url_file")

    printf "\nLoading channels... "
    curl -s "$m3u_url" | grep EXTINF: -A 2 >$tmp_playlist
    # cat "$m3u_url" | grep EXTINF: -A 2 >$tmp_playlist
    printf "Done!\n"

    printf "Parsing channels... "
    channels=()
    url=""

    while IFS= read -r line; do
        if [[ "$line" =~ tvg-name=\"([^\"]+)\" || "$line" =~ tvg-id=\"([^\"]+)\" ]]; then

            name="${BASH_REMATCH[1]}"
            url=""
            title=""

            # pattern="group-title=\"([^\"]+)\""
            pattern="group-title=([^*$]+)"
            if [[ "$line" =~ $pattern ]]; then
                title=" - ${BASH_REMATCH[1]}"
            fi

        elif [[ "$line" == http* ]]; then
            url="$line"
            channels+=("$name$title - [CH:${#channels[@]}] url:$url")
        fi
    done <"$tmp_playlist"

    printf "Done!\n"

    printf "%s\n" "${channels[@]}" >$channels_file
}

iptv_load(){
    if [ ! -z "$m3u" ]; then
        echo "$m3u" >$m3u_url_file
        iptv_save_channels
        echo "Playlist saved. Now run iptv again without a M3U URL."
        exit
    fi

    if [[ $(find "$channels_file" -mtime +1) ]]; then
        printf "Doing a daily update of channels..\n"
        iptv_save_channels
    fi
}