#!/bin/bash
shopt -s nocasematch

{
    type youtube-dl &>/dev/null
    ytdl="$(which youtube-dl)"
} ||
    {
        type yt-dlp &>/dev/null
        ytdl="$(which yt-dlp)"
    } ||
    error "youtube-dl and yt-dlp not installed"

command -v fzf >/dev/null 2>&1 || {
    error "fzf required but not installed"
}    