#!/bin/bash

# settings
GUI=0
DOWNLOAD_DIR=.
KODI_YOUTUBE=0
SEND_RAW=0
SHARE_PORT=8080
REMOTE=""
LOGIN=""
HOST_NAME=""
HEIGHT=""
CYA=""

SEND_TO_KODI_CONF=~/.sendtokodi
if [[ -f "$SEND_TO_KODI_CONF" ]]; then
    source $SEND_TO_KODI_CONF
fi

#iptv def
config_path="$HOME/.config/iptv/"
channels_file="$config_path/channels"
m3u_url_file="$config_path/m3u_url"
tmp_playlist="/tmp/iptvplaylist"
mkdir -p "$config_path"
