#!/usr/bin/env bash

# kodi commands
function kodi_stop() {
    kodi_get_active
    if [[ ! -z $active_player ]]; then
        echo "Request stop:" >&2
        kodi_request '{"jsonrpc": "2.0", "method":"Player.Stop", "params": { "playerid": '"$active_player"' }, "id":0}'
    fi
}
function kodi_next() {
    kodi_get_active
    if [[ ! -z $active_player ]]; then
        echo "Request next:" >&2
        kodi_request '{"jsonrpc": "2.0", "method":"Player.GoTo", "params": { "playerid": '"$active_player"', "to":"next" }, "id":0}'
    fi
}
function kodi_pause() {
    kodi_get_active
    if [[ ! -z $active_player ]]; then
        echo "Request pause:" >&2
        kodi_request '{"jsonrpc": "2.0", "method":"Player.PlayPause", "params": { "playerid": '"$active_player"' }, "id":0}'
    fi
}
function kodi_get_active() {
    kodi_request '{"jsonrpc": "2.0", "method": "Player.GetActivePlayers", "id":0}'
    [[ $? ]] || error "Failed to send - is Kodi running?"
    unset active_player
    if [[ $response ]]; then
        # echo "$response"  >&2
        # active_player=$(echo "$response" | jq -c '.result[] | select(.type | contains("video")).playerid')
        active_player=$(echo "$response" | jq -c '.result[] | select(.type).playerid')
    fi
    # echo "Player id: $active_player"
}
function kodi_shutdown() {
    echo "Request system shutdown:" >&2
    kodi_request '{"jsonrpc": "2.0", "method": "System.Shutdown"}'
}
function kodi_reboot() {
    echo "Request system reboot:" >&2
    kodi_request '{"jsonrpc": "2.0", "method": "System.Reboot"}'
}
function kodi_request(){    
    response="$(curl -X POST -H 'Content-Type: application/json' ${LOGIN:+--user "$LOGIN"} -d "$1"  "http://$REMOTE/jsonrpc" 2>/dev/null)"
    echo "$1" >&2
    echo "$response" >&2
    ! [[ $response =~ '"error":' ]] || error "$response"
}
function check_url() {
    # Get the input string
    local input_string=$1

    # Use regex pattern to check if the string matches the URL format
    local url_pattern="^(http|https)://[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}(/\S*)?$"

    if [[ ! $input_string =~ $url_pattern ]]; then
        unset INPUT
        kodi_main
    fi
}