#!/bin/bash

shopt -s nocasematch

type yt-dlp &>/dev/null
if [[ $? != 0 ]]; then
    error "yt-dlp install required"
fi
type fzf &>/dev/null
if [[ $? != 0 ]]; then
    error "fzf install required"
fi


