#!/bin/bash

shopt -s nocasematch

type yt-dlp &>/dev/null
if [[ $? != 0 ]]; then
    error "yt-dlp required"
fi
type jq &>/dev/null
if [[ $? != 0 ]]; then
    error "jq required"
fi

## moved to iptv_main
# type fzf &>/dev/null
# if [[ $? != 0 ]]; then
#     error "fzf required"
# fi


