#!/bin/bash

show_help() {
    less "$SEND_TO_KODI_DIR/README.md" 
}

version() {
    cd "$SEND_TO_KODI_DIR"
    echo "Local: " $(git describe --abbrev=7 --always  --long --match v* master) 
    echo "remote: " $(git describe --abbrev=7 --always  --long --match v* origin/master) 
}
