#!/usr/bin/env bash

function send_to_kodi_banner() {
    clear
    echo "$SEND_TO_KODI_LOGO_ASCII"
    date
    echo "PID: $$"
    echo "REMOTE: $REMOTE"
    echo "HOSTNAME: $HOST_NAME"
    echo "DOWNLOAD DIR: $DOWNLOAD_DIR"
}

function dlrz_banner() {
    clear
    echo "$DOWNLOAD_LOGO_ASCII"
    date
    echo "PID: $$"
    echo "REMOTE SSH: $REMOTE_SSH"
    echo "REMOTE PATH: $REMOTE_PATH"
    echo "DOWNLOAD DIR: $DOWNLOAD_DIR"
    echo "LIMIT RATE: $LIMIT_RATE"
    echo "CURRENT: $PWD"
}
