#!/usr/bin/env bash

function send_to_kodi_banner() {
    clear
    echo "$SEND_TO_KODI_LOGO_ASCII"
    date
    echo "PID: $$"
    echo "REMOTE: $REMOTE"
    echo "LOCAL: $HOST_NAME"
}

function ytdl_dlrz_banner() {
    clear
    echo "$DOWNLOAD_LOGO_ASCII"
    date
    echo "PID: $$"
    echo "HEIGHT: $RHEIGHT"
    echo "SSH: $REMOTE_SSH"
    echo "DIRECTORY: $DESTINATION_PATH"
    echo "CURRENT: $PWD"
}
