#!/usr/bin/env bash

SEND_TO_KODI_HOME="$HOME/.config/send_to_kodi"
SEND_TO_KODI_CONF="$SEND_TO_KODI_HOME/.sendtokodi"

if [[ ! -f "$SEND_TO_KODI_CONF" ]]; then

mkdir -p "$SEND_TO_KODI_HOME"

cat > "$SEND_TO_KODI_CONF" << EOF
#!/usr/bin/env bash
GUI=0
DOWNLOAD_DIR=.
KODI_YOUTUBE=0
SEND_RAW=0
REMOTE="kodibox:8080"
LOGIN="user:pass"
HOST_NAME="$(hostname -I | awk '{print $1}')" #ipv4
SHARE_PORT=8080
RESOLUTION_HEIGHT=""
BYPASS_LIST=("soundcloud.com" "yp.shoutcast.com")
#display available formats
LISTFORMATS=0
EOF

fi

source "$SEND_TO_KODI_CONF"

#iptv def
config_path="$HOME/.config/iptv/"
channels_file="$config_path/channels"
m3u_url_file="$config_path/m3u_url"
tmp_playlist="/tmp/iptvplaylist"
mkdir -p "$config_path"
