#!/usr/bin/env bash

SEND_TO_KODI_HOME="$HOME/.config/send_to_kodi"
SEND_TO_KODI_CONF="$SEND_TO_KODI_HOME/.sendtokodi"
SEND_TO_KODI_CUSTOM_COMMANDS="$HOME/.config/send_to_kodi/send_to_kodi_commands"

if [[ ! -f "$SEND_TO_KODI_CONF" ]]; then
  mkdir -p "$SEND_TO_KODI_HOME"
  #HOST_NAME="$(hostname -I | awk '{print $1}' || hostname -i )" #ipv4 is hostname not visible
  cat >"$SEND_TO_KODI_CONF" <<EOF
#!/usr/bin/env bash
GUI=0
DOWNLOAD_DIR=~/Download/
KODI_YOUTUBE=0
SEND_RAW=0
SHARE_PORT=8080
REMOTE="kodibox:8080"
LOGIN="username:password"
HOST_NAME="$(hostname -I | awk '{print $1}')" #ipv4 is hostname not visible | hostname -i
USER_AGENT="Mozilla/5.0 (Android 14; Mobile; rv:68.0) Gecko/68.0 Firefox/128.0"
#RESOLUTION_HEIGHT="360"
RESOLUTION_JSON='[
    {"res":"360", "value":["twitch.tv","youtube.com"]}
]'
LISTFORMATS=0
EOF

fi

source "$SEND_TO_KODI_CONF"

# custom commands can be defined in this file
if [[ ! -f "$SEND_TO_KODI_CUSTOM_COMMANDS" ]]; then
  mkdir -p "$SEND_TO_KODI_CUSTOM_COMMANDS"
  cat >"$SEND_TO_KODI_CUSTOM_COMMANDS" <<EOF
#!/usr/bin/env bash
            # if [[ '"$INPUT"' =~ ^(respring)$ ]]; then
            #     unset INPUT
            #     ssh ipad respring
            #     kodi_main
            # fi
EOF

fi

#iptv def
config_path="$HOME/.config/iptv/"
channels_file="$config_path/channels"
m3u_url_file="$config_path/m3u_url"
tmp_playlist="/tmp/iptvplaylist"
mkdir -p "$config_path"
