#!/usr/bin/env bash

msg=""
if ! type yt-dlp &>/dev/null; then
    msg=" yt-dlp"
fi
if ! type jq &>/dev/null; then
    msg=${msg}" jq"
fi
if ! type ffmpeg &>/dev/null; then
    msg=${msg}" ffmpeg"
fi
if [[ -n $msg ]]; then
    msg="Requirements missing :"${msg}
    echo "$msg"
    exit 1
fi






