#!/usr/bin/env bash

msg=""
if ! type yt-dlp &>/dev/null; then
    msg=" yt-dlp"
fi
if ! type jq &>/dev/null; then
    msg=${msg}" jq"
fi
if ! type ffmpeg &>/dev/null; then
    msg=${msg}" ffmpeg"
fi
if ! type curl &>/dev/null; then
    msg=${msg}" curl"
fi
if ! type fzf &>/dev/null; then
    msg=${msg}" fzf"
fi
if [[ -n $msg ]]; then
    msg="Missing Requirements:"${msg}
    echo "$msg"
    exit 1
fi






